version: 0.0.3

Cooldown: 0

language:
  windowname: "&0&lMounts!"
  prefix: "&7[Mounts] "
  mounted: "&eYou have mounted {mountname}!"
  invalid_location: "&cCould not summon mount at this location, move to a more open location!"
  no_mounts: "&cYou do not have any available mounts!"
  cool_down: "&cCooling Down!"

Paths:
  Speed: 0.5
  Blocks:
  - GRASS_PATH
  - GRAVEL
