name: EpicMounts
main: land.face.mounts.EpicMountsPlugin

version: 1.0.0
api-version: 1.16
depend: [Facecore]
description: A plugin that provides a permissions based mount system

authors: [Faceguy, Lorinthio, Lozke]

commands:
  mounts:
    description: Opens up your mount options!